dist: xenial
sudo: required
notifications:
  email: false
language: python
cache: pip
python:
  - "3.5"
  - "3.6"
  - "pypy3"
services:
  - postgresql
addons:
  chrome: stable
  postgresql: 9.6
  sauce_connect:
    username: catmaid
  jwt:
    secure: "hj6rvwzab8ptfMKvRyqCZnWqun2uEv69nLCGxLXiDk9QZOUv/UG8PU060m6DTHtYE8iJw5E6qhTIhLKlpPadYptkxmiOXVGKlU6jam8SLKsSbHbdFsoziIPnU4mpqNgjvZ7Xb7xoTmYcd15G7Du3qgTHc28TeT5F9XnyfyDCH7M="
before_install:
  - mkdir tmp
  - travis_retry sudo apt-get update -y -qq
  - bash scripts/travis/install_postgres.sh
  - bash scripts/travis/install_python.sh
install:
  # Install requirements for running CATMAID and its unit tests
  - ./scripts/travis/install_requirements.sh
  - pip install coveralls flake8
  - npm install --only=dev
  - npm bin
  - export PATH=$(npm bin):$PATH
before_script:
  # Set up and start postgres, create database, write config files
  - ./scripts/travis/setup_database.sh
  - ./scripts/travis/configure_catmaid.sh
script:
  - flake8 --config=.travis.flake8 --statistics --count --exit-zero -q -q django
  - jshint --config=.travis.jshintrc --exclude-path=.travis.jshintignore django/applications
  - $TRAVIS_BUILD_DIR/node_modules/.bin/jsdoc -r django/applications/catmaid/static/js
  - cd django/applications/catmaid/static/css
  - $TRAVIS_BUILD_DIR/node_modules/.bin/csslint .
  - cd $TRAVIS_BUILD_DIR
  - cd django/projects
  - python manage.py migrate --noinput
  - python manage.py collectstatic --link --noinput
  - coverage run manage.py test catmaid.tests
  # Remove login requirement from QUnit test page
  - sed -i 's/login_required(\([^)]*\))/\1/g' ../applications/catmaid/urls.py
  - python -Wall -Wignore::ImportWarning manage.py runserver &
  - sleep 5
  - cd ../..
  # Run QUnit through karma in headless Chrome
  - karma start karma.conf.js
after_success:
  - cd django/projects && coveralls
